import { CreateAttributesValuesInput, UpdateAttributesValuesInput } from '@cbidigital/aqua';
import { Nullable } from '@heronjs/common';
import { CreateProfileAddressInput, UpdateProfileAddressInput } from '.';
import { GenderEnum, ProfileStatusEnum } from '../enums';
declare type CreateProfileAddressInnerInput = Omit<CreateProfileAddressInput, 'profileId'>;
export declare type CreateProfileInput = {
    userId: Nullable<string>;
    firstName: Nullable<string>;
    lastName: Nullable<string>;
    email: Nullable<string>;
    gender: Nullable<GenderEnum>;
    dob: Nullable<string>;
    phone: Nullable<string>;
    identityNum: Nullable<string>;
    avatar: Nullable<string>;
    profession: Nullable<string>;
    status?: ProfileStatusEnum;
    addressInfo?: CreateProfileAddressInnerInput;
    attributeValues?: CreateAttributesValuesInput;
    parentId?: Nullable<string>;
    typeId?: Nullable<string>;
    targetId?: Nullable<string>;
    code?: Nullable<string>;
};
export declare class CreateProfileInputModel implements CreateProfileInput {
    readonly userId: Nullable<string>;
    readonly firstName: Nullable<string>;
    readonly lastName: Nullable<string>;
    readonly email: Nullable<string>;
    readonly gender: Nullable<GenderEnum>;
    readonly dob: Nullable<string>;
    readonly phone: Nullable<string>;
    readonly identityNum: Nullable<string>;
    readonly avatar: Nullable<string>;
    readonly profession: Nullable<string>;
    readonly status?: ProfileStatusEnum | undefined;
    readonly addressInfo?: CreateProfileAddressInnerInput;
    readonly attributeValues?: CreateAttributesValuesInput;
    readonly typeId?: Nullable<string>;
    readonly parentId?: Nullable<string>;
    readonly targetId?: Nullable<string>;
    readonly code?: Nullable<string>;
}
export declare type CreateProfileOutput = void;
export declare type UpdateProfileInput = {
    userId?: Nullable<string>;
    firstName?: Nullable<string>;
    lastName?: Nullable<string>;
    email?: Nullable<string>;
    gender?: Nullable<GenderEnum>;
    dob?: Nullable<Date>;
    phone?: Nullable<string>;
    identityNum?: Nullable<string>;
    avatar?: Nullable<string>;
    profession?: Nullable<string>;
    status?: ProfileStatusEnum;
    addressInfo?: UpdateProfileAddressInput;
    attributeValues?: UpdateAttributesValuesInput;
    parentId?: Nullable<string>;
    typeId?: Nullable<string>;
    targetId?: Nullable<string>;
};
export declare class UpdateProfileInputModel implements UpdateProfileInput {
    readonly userId?: Nullable<string>;
    readonly firstName?: Nullable<string>;
    readonly lastName?: Nullable<string>;
    readonly email?: Nullable<string>;
    readonly gender?: Nullable<GenderEnum>;
    readonly dob?: Nullable<Date>;
    readonly phone?: Nullable<string>;
    readonly identityNum?: Nullable<string>;
    readonly avatar?: Nullable<string>;
    readonly profession?: Nullable<string>;
    readonly status?: ProfileStatusEnum | undefined;
    readonly addressInfo?: UpdateProfileAddressInput;
    readonly attributeValues?: UpdateAttributesValuesInput;
    readonly typeId?: Nullable<string>;
    readonly parentId?: Nullable<string>;
    readonly targetId?: Nullable<string>;
}
export declare type UpdateProfileOutput = void;
export declare type DeleteProfileInput = void;
export declare type DeleteProfileOutput = void;
export {};
